sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - node_cache
  - node_shrinkwrap
  - $HOME/.npm
before_install:
- gem install sass -v 3.4.24
script:
- node_modules/.bin/grunt travis
after_success:
- node deploy-docs.js
- if [[ "$TRAVIS_BRANCH" = "master" || "$TRAVIS_TAG" != "" ]]; then node_modules/.bin/grunt dists; fi
notifications:
  slack:
    secure: aQXFk2/MxX5eR2JM90xWAA9YX03QArY1ejUmnP/NkFHbB4zzKZblACjEeDTDTDCThZpXhrganX2nDWrWFrrXbOG28wKrRhEZSULPAgyiWGpfkMoT44fKmgh+eZ5C/isMF2eeQCrYo3EQCMxfCKxNaBhyLc+jr/Sm232zU2LaXo8=
