version: '{build}'
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "6"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - node_modules/.bin/grunt appveyor
artifacts:
  - path: build\dist\**\*.nupkg
    name: Nuget Package
after_build:
  - ps: Get-ChildItem build\dist\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
matrix:
  fast_finish: true
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
  - node_cache -> package.json                                          # local npm cache
  - node_shrinkwrap -> package.json                                     # local shrinkwrap cache